source 'https://rubygems.org'
gem 'rdf', '=1.1.6'
gem 'sparql','=1.1.4' 
gem 'sinatra'
gem 'sinatra-linkeddata'
gem 'haml'
gem 'bio-bgzf'
gem 'sequel'
gem 'jdbc-sqlite3'
gem 'tilt', '>= 1.3.4', '~> 1.3'
gem 'json'
gem "sinatra-cross_origin", "~> 0.3.1"
#require 'multi_json'
